### ISSUE TITLE
Code missing from NPM

### ISSUE THREAD

**Issue by rikukissa** [radubrehar/react-accordion#1]
![image](https://cloud.githubusercontent.com/assets/1206987/6469531/008df390-c1e6-11e4-9d0a-ba09410c7954.png)
Both source and built files are missing from npm

**Comment by radubrehar** [comment]
Yes, code is just on github, not on npm yet. Please use the code on github, in your package.json specify "react-accordion": "radubrehar/react-accordion", and npm will pick it up from github.

I'm still polishing the component before publishing the code to npm. As soon as the component is production-ready I will be pushing it to npm as well and will update the documentation.

**Comment by rikukissa** [comment]
Alright, thanks for the info! I installed the project from github yesterday, but couldn't find any styles for the component so I gave up. Apparently the styles are included to the component itself?

**Comment by radubrehar** [comment]
For now, the accordion does not impose any styles on the user, there are only some minimum defaults included in the component itself.

Check https://github.com/radubrehar/react-accordion/blob/master/index.jsx for an example if you haven't already. You can specify an accordion item title using the `data-title` attribute on the children of the accordion. Otherwise, the first child of each item will be used as a title.

**Comment by rikukissa** [comment]
Thanks, Ill give it a try later today!
